#!/bin/bash

log_file=`cat ./apache_log.txt`

items=`cat $log_file | grep 404 | awk '{print $1, $9, $4}' | grep -v 200 | grep -v "::1" | sed 's/\[/\ /g' | cut -d: -f1 | awk '{print $4, $1, $3}' | uniq  -c | sort -nr |/usr/bin/awk '{print "<td bgcolor=white><font color=blue><h6><strong>"$1","$2","$3,"</td></tr>"}'`

split(){ arr=($items); }
IFS=','$'\n' split

printf "<td bgcolor=white><font color=blue><h6><strong> %s \n" "${arr[@]}"
