#!/bin/bash

items=`df -h | grep -v Filesystem |/usr/bin/awk '{print "<td bgcolor=white><font color=blue><h6><strong>"$1","$2","$3","$4","$5","$6"</td></tr>"}'`

split(){ arr=($items); }
IFS=','$'\n' split

printf "<td bgcolor=white><font color=blue><h6><strong> %s \n" "${arr[@]}"