#!/bin/bash

items=`netstat -tun  | grep -v "servers" | grep -v "Address" | sort -nr | uniq -c |/usr/bin/awk '{print "<td bgcolor=white><font color=blue><h6><strong>"$1","$2","$5","$6","$7"</td></tr>"}'`

split(){ arr=($items); }
IFS=','$'\n' split

printf "<td bgcolor=white><font color=blue><h6><strong> %s \n" "${arr[@]}"




