#!/bin/bash

items=`ps aux | grep -v USER |/usr/bin/awk '{print "<td bgcolor=white><font color=blue><h6><strong>"$1","$2","$3","$4","$6","$7","$8","$11"</td></tr>"}'`

split(){ arr=($items); }
IFS=','$'\n' split

printf "<td bgcolor=white><font color=blue><h6><strong> %s \n" "${arr[@]}"




